### ISSUE TITLE
"Forceloaded blocks" does not show map blocks loaded by "techage"

### ISSUE THREAD

**Issue by Niklp09** [minetest-monitoring/monitoring#23]
"Forceloaded blocks" does not show map blocks loaded by "techage"

**Comment by BuckarooBanzay** [comment]
The current mechanism just checks the `force_loaded.txt` file because there isn't an api for enumerating forceloaded blocks (yet)

https://github.com/minetest-monitoring/monitoring/blob/ef31cb0dfe779d3a4fbb406d5a91486ebc6a75d3/builtin/forceload_blocks.lua#L23-L30

If the `techage` forceloaded blocks aren't in there then i guess it works differently, any idea how it manages to "forceload" blocks?

**Comment by joe7575** [comment]
techage simply calls `minetest.forceload_block(pos, true)` for each placed forceload block
(https://github.com/joe7575/techage/blob/master/basic_machines/forceload.lua#L275)

**Comment by BuckarooBanzay** [comment]
Ah, those are transient forceloads, yeah, no idea how to enumerate those :/ this might need an engine-change (api) in order to work
